name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
        id: update
        with:
          pr-title: "Update Nix flake inputs"
          pr-labels: |
            dependencies
            automated
      - name: Merge
        if: ${{ steps.update.outputs.pull-request-number != '' }}
        run: gh pr merge --auto "${{ steps.update.outputs.pull-request-number }}" --rebase
        
